# Generated by Django 3.0.5 on 2020-05-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], default='H', max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('telephone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('identifiant', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nombreDePersonne', models.PositiveIntegerField()),
                ('numeroDeRue', models.PositiveIntegerField()),
                ('nomDeRue', models.CharField(max_length=100)),
                ('codePostal', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddConstraint(
            model_name='foyer',
            constraint=models.UniqueConstraint(fields=('numeroDeRue', 'nomDeRue'), name='adresse_unique'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='identifiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccueilPage.Foyer'),
        ),
    ]
