# Generated by Django 3.0.6 on 2020-06-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('identifiant', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nom_entreprise', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=50)),
                ('code_naf', models.CharField(max_length=50)),
                ('numero_siret', models.CharField(max_length=50)),
                ('adresse_siege_sociale', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('nom', models.CharField(default='Inconnue', max_length=30, primary_key=True, serialize=False)),
                ('typehandicap', models.CharField(choices=[('M', 'Handicap mental'), ('P', 'Handicap Physique'), ('S', 'Handicap Sensoriel'), ('C', 'Handicap Cognitif'), ('Y', 'Handicap psychique'), ('O', 'Polyhandicap')], default='O', max_length=1)),
                ('desc', models.CharField(default='sans', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('identifiant', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dateDeNaissance', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('codePostal', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=50)),
                ('cartehandicap', models.BooleanField(default=False)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme'), ('N', 'Non Binaire')], default='H', max_length=1)),
                ('centresInterets', models.CharField(default='aucun', max_length=500)),
                ('etude', models.CharField(choices=[('S', 'Sans Etude'), ('B', 'Brevet des collèges'), ('P', 'Formation pro'), ('G', 'Bts'), ('F', 'DUT'), ('C', 'Bac'), ('D', 'Bac + 3'), ('E', 'Bac + 5'), ('F', 'Bac + 8')], default='S', max_length=1)),
                ('nom_diplome', models.CharField(default='aucun', max_length=255)),
                ('competence', models.CharField(default='aucun', max_length=800)),
                ('descriptif_membre', models.CharField(default='aucun', max_length=1000)),
                ('experience', models.CharField(default='aucun', max_length=1000)),
                ('handicap', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AccueilPage.Handicap')),
            ],
        ),
    ]
